CREATE TABLE IF NOT EXISTS `cedrus_erp`.`PRODUTO_UNIDADE` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `SIGLA` VARCHAR(10) NULL,
  `DESCRICAO` VARCHAR(250) NULL,
  `PODE_FRACIONAR` CHAR(1) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `cedrus_erp`.`TRIBUT_GRUPO_TRIBUTARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(100) NULL,
  `ORIGEM_MERCADORIA` CHAR(1) NULL,
  `OBSERVACAO` TEXT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `cedrus_erp`.`PRODUTO_TIPO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODIGO` CHAR(2) NULL,
  `DESCRICAO` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `cedrus_erp`.`PRODUTO_GRUPO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NULL,
  `DESCRICAO` VARCHAR(250) NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `cedrus_erp`.`PRODUTO_SUBGRUPO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO_GRUPO` INT NOT NULL,
  `NOME` VARCHAR(100) NULL,
  `DESCRICAO` VARCHAR(250) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PRODUTO_SUBGRUPO_PRODUTO_GRUPO1_idx` (`ID_PRODUTO_GRUPO` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTO_SUBGRUPO_PRODUTO_GRUPO1` FOREIGN KEY (`ID_PRODUTO_GRUPO`) REFERENCES `cedrus_erp`.`PRODUTO_GRUPO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `cedrus_erp`.`PRODUTO` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO_UNIDADE` INT UNSIGNED NOT NULL,
  `ID_TRIBUT_GRUPO_TRIBUTARIO` INT NOT NULL,
  `ID_PRODUTO_TIPO` INT NOT NULL,
  `ID_PRODUTO_SUBGRUPO` INT NOT NULL,
  `GTIN` VARCHAR(14) NULL COMMENT 'Código GTIN do produto com até 14 caracteres',
  `CODIGO_INTERNO` VARCHAR(50) NULL,
  `NOME` VARCHAR(100) NULL,
  `DESCRICAO` VARCHAR(250) NULL,
  `DESCRICAO_PDV` VARCHAR(30) NULL,
  `VALOR_COMPRA` DECIMAL(18,6) NULL,
  `VALOR_VENDA` DECIMAL(18,6) NULL,
  `QUANTIDADE_ESTOQUE` DECIMAL(18,6) NULL,
  `ESTOQUE_MINIMO` DECIMAL(18,6) NULL,
  `ESTOQUE_MAXIMO` DECIMAL(18,6) NULL,
  `CODIGO_NCM` VARCHAR(8) NULL,
  `IAT` CHAR(1) NULL COMMENT 'A=ARREDONDAMENTO | T=TRUNCAMENTO',
  `IPPT` CHAR(1) NULL COMMENT 'P=PROPRIO | T=TERCEIRO',
  `TIPO_ITEM_SPED` CHAR(2) NULL,
  `TAXA_IPI` DECIMAL(18,6) NULL,
  `TAXA_ISSQN` DECIMAL(18,6) NULL,
  `TAXA_PIS` DECIMAL(18,6) NULL,
  `TAXA_COFINS` DECIMAL(18,6) NULL,
  `TAXA_ICMS` DECIMAL(18,6) NULL,
  `CST` CHAR(3) NULL,
  `CSOSN` CHAR(4) NULL,
  `TOTALIZADOR_PARCIAL` VARCHAR(10) NULL,
  `CODIGO_BALANCA` INT UNSIGNED NULL,
  `PAF_P_ST` CHAR(1) NULL,
  `HASH_REGISTRO` VARCHAR(32) NULL,
  `VALOR_CUSTO` DECIMAL(18,6) NULL,
  `SITUACAO` CHAR(1) NULL COMMENT 'A=ATIVO\nI=INATIVO',
  `CODIGO_CEST` VARCHAR(7) NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_UNIDADE_PRODUTO_IDX` (`ID_PRODUTO_UNIDADE` ASC) VISIBLE,
  INDEX `FK_PRODUTO_TRIBUT_GRUPO_TRIBUTARIO1_IDX` (`ID_TRIBUT_GRUPO_TRIBUTARIO` ASC) VISIBLE,
  INDEX `FK_PRODUTO_PRODUTO_TIPO1_IDX` (`ID_PRODUTO_TIPO` ASC) VISIBLE,
  INDEX `FK_PRODUTO_PRODUTO_SUBGRUPO1_IDX` (`ID_PRODUTO_SUBGRUPO` ASC) VISIBLE,
  CONSTRAINT `FK_PRODUTO_PRODUTO_UNIDADE` FOREIGN KEY (`ID_PRODUTO_UNIDADE`) REFERENCES `cedrus_erp`.`PRODUTO_UNIDADE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_TRIBUT_GRUPO_TRIBUTARIO1` FOREIGN KEY (`ID_TRIBUT_GRUPO_TRIBUTARIO`) REFERENCES `cedrus_erp`.`TRIBUT_GRUPO_TRIBUTARIO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_PRODUTO_TIPO1` FOREIGN KEY (`ID_PRODUTO_TIPO`) REFERENCES `cedrus_erp`.`PRODUTO_TIPO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_PRODUTO_SUBGRUPO1` FOREIGN KEY (`ID_PRODUTO_SUBGRUPO`) REFERENCES `cedrus_erp`.`PRODUTO_SUBGRUPO` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;